include(ExternalProject)

ExternalProject_Add(ep_jpeg-turbo
    GIT_REPOSITORY      https://github.com/libjpeg-turbo/libjpeg-turbo.git
    GIT_TAG             3.0.3
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/fakeroot
        -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib
        -DENABLE_SHARED=FALSE
        -DENABLE_STATIC=TRUE
        -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE
        -DPNG_SUPPORTED=off
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
)