include(ExternalProject)

ExternalProject_Add(ep_ssi
    DOWNLOAD_COMMAND ""
    DEPENDS ${DEPENDENCIES}
    SOURCE_DIR ${PROJECT_SOURCE_DIR}
    CMAKE_ARGS -DUSE_SUPERBUILD=OFF -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/fakeroot -DCUSTOM_LIB_PATH=${THIRD_PARTY_LIB_PATH} ${EXTRA_CMAKE_ARGS}
)