include(ExternalProject)

ExternalProject_Add(ep_ssi_test
    DOWNLOAD_COMMAND ""
    DEPENDS ${DEPENDENCIES} ep_ssi
    BUILD_ALWAYS 1
    SOURCE_DIR ${PROJECT_SOURCE_DIR}/test
    CMAKE_ARGS
        -DCUSTOM_LIB_PATH=${THIRD_PARTY_LIB_PATH}
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
    INSTALL_COMMAND ""
    TEST_COMMAND ${CTest_EXECUTABLE} --test-dir <BINARY_DIR>
)