include(ExternalProject)

ExternalProject_Add(ep_ssi_test
    DOWNLOAD_COMMAND ""
    DEPENDS ${DEPENDENCIES} ep_ssi
    SOURCE_DIR ${PROJECT_SOURCE_DIR}/test
    CMAKE_ARGS -DCMAKE_VERBOSE_MAKEFILE=ON -DCUSTOM_LIB_PATH=${THIRD_PARTY_LIB_PATH}
    INSTALL_COMMAND ""
    TEST_COMMAND ${CTest_EXECUTABLE} --test-dir <BINARY_DIR>
)